-- Ajout des champs profil utilisateur
ALTER TABLE users ADD COLUMN IF NOT EXISTS city VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS "bacOption" VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS university VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS field VARCHAR;
