#!/usr/bin/env python3
"""Corrige les accents manquants dans les textes UI français (sans toucher aux identifiants techniques)."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Identifiants techniques à préserver (placeholders temporaires)
PROTECTED: list[tuple[str, str]] = [
    ('"etudiant"', "__PROT_ROLE_ETUDIANT__"),
    ("'etudiant'", "__PROT_ROLE_ETUDIANT__"),
    ('"bachelier"', "__PROT_ROLE_BACHELIER__"),
    ("'bachelier'", "__PROT_ROLE_BACHELIER__"),
    ('"admin"', "__PROT_ROLE_ADMIN__"),
    ('/universites', "__PROT_PATH_UNIVERSITES__"),
    ('id: "universites"', '__PROT_ID_UNIVERSITES__'),
    ('href: "/universites"', '__PROT_HREF_UNIVERSITES__'),
    ('link: "/universites"', '__PROT_LINK_UNIVERSITES__'),
    ('z.literal("etudiant")', '__PROT_Z_ETUDIANT__'),
    ('z.literal("bachelier")', '__PROT_Z_BACHELIER__'),
    ('role: "etudiant"', '__PROT_ROLE_FIELD_ETUDIANT__'),
    ('role: "bachelier"', '__PROT_ROLE_FIELD_BACHELIER__'),
    ('UserRole = "etudiant"', '__PROT_TYPE_ETUDIANT__'),
    ('UserRole = "bachelier"', '__PROT_TYPE_BACHELIER__'),
    ('=== "etudiant"', '__PROT_EQ_ETUDIANT__'),
    ('!== "etudiant"', '__PROT_NEQ_ETUDIANT__'),
    ('=== "bachelier"', '__PROT_EQ_BACHELIER__'),
    ('!== "bachelier"', '__PROT_NEQ_BACHELIER__'),
    ('role === "etudiant"', '__PROT_ROLE_EQ_ETUDIANT__'),
    ('role === "bachelier"', '__PROT_ROLE_EQ_BACHELIER__'),
    ('option.id', '__PROT_OPTION_ID__'),  # avoid breaking id fields
]

# Remplacements ordonnés (expressions longues d'abord)
REPLACEMENTS: list[tuple[str, str]] = [
    # Expressions composées
    ("Universites & Ecoles", "Universités & Écoles"),
    ("Universites & ecoles", "Universités & écoles"),
    ("universites & ecoles", "universités & écoles"),
    ("Politique de confidentialite", "Politique de confidentialité"),
    ("politique de confidentialite", "politique de confidentialité"),
    ("Orientation personnalisee", "Orientation personnalisée"),
    ("Conseillers etudiants", "Conseillers étudiants"),
    ("Communaute active", "Communauté active"),
    ("Opportunites locales", "Opportunités locales"),
    ("Generateur CV", "Générateur CV"),
    ("Generateur de CV", "Générateur de CV"),
    ("Suivi academique", "Suivi académique"),
    ("Plateforme etudiante", "Plateforme étudiante"),
    ("La plateforme etudiante", "La plateforme étudiante"),
    ("La reussite, a deux", "La réussite, à deux"),
    ("Reussis plus vite", "Réussis plus vite"),
    ("des etudiants deja en filiere", "des étudiants déjà en filière"),
    ("repondent a tes questions", "répondent à tes questions"),
    ("Commence a explorer", "Commence à explorer"),
    ("filieres les plus adaptees", "filières les plus adaptées"),
    ("Jeune etudiante en bibliotheque", "Jeune étudiante en bibliothèque"),
    ("Jeune etudiant en bibliotheque", "Jeune étudiant en bibliothèque"),
    ("choisir ta filiere", "choisir ta filière"),
    ("a une etape", "à une étape"),
    ("aide-les a choisir", "aide-les à choisir"),
    ("bonne filiere", "bonne filière"),
    ("Accompagne de nouveaux etudiants", "Accompagne de nouveaux étudiants"),
    ("Developpe ton reseau", "Développe ton réseau"),
    ("Contribue a ta communaute", "Contribue à ta communauté"),
    ("du bac a l'emploi", "du bac à l'emploi"),
    ("a l'emploi", "à l'emploi"),
    ("a chaque etape", "à chaque étape"),
    ("12 etablissements", "12 établissements"),
    ("Selectionne ton option", "Sélectionne ton option"),
    ("Indique ton universite", "Indique ton université"),
    ("Indique ta filiere", "Indique ta filière"),
    ("6 caracteres", "6 caractères"),
    ("Inscription reussie mais connexion echouee", "Inscription réussie mais connexion échouée"),
    ("Verifie ta connexion et reessaie", "Vérifie ta connexion et réessaie"),
    ("Creer un compte", "Créer un compte"),
    ("Securise ton compte", "Sécurise ton compte"),
    ("Etape 1 sur 2", "Étape 1 sur 2"),
    ("Etape 2 sur 2", "Étape 2 sur 2"),
    ("email ou telephone", "email ou téléphone"),
    ("Email ou telephone", "Email ou téléphone"),
    ("numero de telephone", "numéro de téléphone"),
    ("Universite (UGANC", "Université (UGANC"),
    ("Filiere (Informatique, Medecine", "Filière (Informatique, Médecine"),
    ("Deja un compte", "Déjà un compte"),
    ("Session expiree ou connexion refusee. Reessaie", "Session expirée ou connexion refusée. Réessaie"),
    ("Se connecter a BacheliO", "Se connecter à BacheliO"),
    ("Mot de passe oublie", "Mot de passe oublié"),
    ("ci-apres", "ci-après"),
    ("accompagnement etudiant", "accompagnement étudiant"),
    ("relative a vos donnees", "relative à vos données"),
    ("Donnees collectees", "Données collectées"),
    ("Donnees techniques", "Données techniques"),
    ("numero de telephone", "numéro de téléphone"),
    ("de facon chiffree", "de façon chiffrée"),
    ("Profil academique", "Profil académique"),
    ("universite, filiere", "université, filière"),
    ("consultees (a des fins de securite et d'amelioration)", "consultées (à des fins de sécurité et d'amélioration)"),
    ("Vos donnees sont utilisees", "Vos données sont utilisées"),
    ("Creer et securiser", "Créer et sécuriser"),
    ("a des tiers", "à des tiers"),
    ("Base legale", "Base légale"),
    ("le cas echeant", "le cas échéant"),
    ("interet legitime a securiser et ameliorer", "intérêt légitime à sécuriser et améliorer"),
    ("delai raisonnable", "délai raisonnable"),
    ("obligation legale", "obligation légale"),
    ("logs de securite", "logs de sécurité"),
    ("peuvent etre traitees", "peuvent être traitées"),
    ("hebergement", "hébergement"),
    ("garanties contractuelles", "garanties contractuelles"),
    ("acces restreints", "accès restreints"),
    ("activite suspecte a contact", "activité suspecte à contact"),
    ("l'acces, la rectification", "l'accès, la rectification"),
    ("traitement de vos donnees", "traitement de vos données"),
    ("vous opposer a certains", "vous opposer à certains"),
    ("bacheliers et etudiants", "bacheliers et étudiants"),
    ("avant de creer un compte", "avant de créer un compte"),
    ("peut etre mise a jour", "peut être mise à jour"),
    ("Derniere mise a jour", "Dernière mise à jour"),
    ("utilise et protege vos donnees", "utilise et protège vos données"),
    ("Retour a l'inscription", "Retour à l'inscription"),
    ("Retour a l'accueil", "Retour à l'accueil"),
    ("Parler a un mentor", "Parler à un mentor"),
    ("Parler a l'assistant", "Parler à l'assistant"),
    ("Demander a Kampus", "Demander à Kampus"),
    ("premier a lancer", "premier à lancer"),
    ("premier a repondre", "premier à répondre"),
    ("premier a partager", "premier à partager"),
    ("Connecte-toi pour utiliser", "Connecte-toi pour utiliser"),  # Connecté would break imperative
    ("Session expiree", "Session expirée"),
    ("Impossible de verifier ton quota", "Impossible de vérifier ton quota"),
    ("Donnees invalides", "Données invalides"),
    ("Reponse vide", "Réponse vide"),
    ("Erreur lors de l'appel a l'assistant", "Erreur lors de l'appel à l'assistant"),
    ("Ecris ton message", "Écris ton message"),
    ("Ecris un message", "Écris un message"),
    ("Ecris ta reponse", "Écris ta réponse"),
    ("Se deconnecter", "Se déconnecter"),
    ("Deconnexion", "Déconnexion"),
    ("Gere ton compte", "Gère ton compte"),
    ("Filiere, universite et annee", "Filière, université et année"),
    ("Filiere et universite pre-remplies", "Filière et université pré-remplies"),
    ("4eme annee", "4e année"),
    ("Creneaux disponibles", "Créneaux disponibles"),
    ("Creneau", "Créneau"),
    ("creneau", "créneau"),
    ("Rendez-vous reserve", "Rendez-vous réservé"),
    ("apparaitront ici bientot", "apparaîtront ici bientôt"),
    ("apparaitront", "apparaîtront"),
    ("inscris-toi pour", "inscris-toi pour"),
    ("message envoye", "message envoyé"),
    ("notifie", "notifié"),
    ("Selectionne un", "Sélectionne un"),
    ("Selectionne", "Sélectionne"),
    ("Selectionner", "Sélectionner"),
    ("selectionner un fichier", "sélectionner un fichier"),
    ("Vie etudiante", "Vie étudiante"),
    ("Decris ta question en detail", "Décris ta question en détail"),
    ("Decris brievement", "Décris brièvement"),
    ("Referentiel", "Référentiel"),
    ("referentiel", "référentiel"),
    ("etablissement trouve", "établissement trouvé"),
    ("mot-cle", "mot-clé"),
    ("reinitialise", "réinitialise"),
    ("Tu hesites", "Tu hésites"),
    ("hesites encore", "hésites encore"),
    ("connait le", "connaît le"),
    ("Non renseignee", "Non renseignée"),
    ("enregistree", "enregistrée"),
    ("enregistre", "enregistré"),
    ("ajoutees", "ajoutées"),
    ("ajoutes", "ajoutés"),
    ("Complete ton profil", "Complète ton profil"),
    ("Cree un CV", "Crée un CV"),
    ("evenements universitaires", "événements universitaires"),
    ("rentrees", "rentrées"),
    ("feries", "fériés"),
    ("Entrepreneuriat etudiant", "Entrepreneuriat étudiant"),
    ("Decouvre les initiatives", "Découvre les initiatives"),
    ("d'etudes", "d'études"),
    ("publiees", "publiées"),
    ("bientot publiees", "bientôt publiées"),
    ("regulierement", "régulièrement"),
    ("Bibliotheque de ressources", "Bibliothèque de ressources"),
    ("Bibliotheque", "Bibliothèque"),
    ("accede a des", "accède à des"),
    ("communaute etudiante", "communauté étudiante"),
    ("Carriere", "Carrière"),
    ("anciens etudiants", "anciens étudiants"),
    ("publies", "publiés"),
    ("generation d'etudiants", "génération d'étudiants"),
    ("Evenements", "Événements"),
    ("Evenement", "Événement"),
    ("temps reel", "temps réel"),
    ("Illimite", "Illimité"),
    ("periode", "période"),
    ("Derniere activite", "Dernière activité"),
    ("Date debut", "Date début"),
    ("Debut", "Début"),
    ("Annee diplome", "Année diplôme"),
    ("initiatives etudiantes", "initiatives étudiantes"),
    ("opportunites", "opportunités"),
    ("Opportunites", "Opportunités"),
    ("Mettre a jour", "Mettre à jour"),
    ("Recois une notification sur ton telephone quand un bachelier t'ecrit", "Reçois une notification sur ton téléphone quand un bachelier t'écrit"),
    ("Repondre", "Répondre"),
    ("Bientot disponible", "Bientôt disponible"),
    ("Bientot", "Bientôt"),
    ("fonctionnalite en preparation", "fonctionnalité en préparation"),
    ("bientot disponible", "bientôt disponible"),
    ("Erreur reseau", "Erreur réseau"),
    ("Verifie ta connexion", "Vérifie ta connexion"),
    ("Verifie", "Vérifie"),
    ("Reessaie", "Réessaie"),
    ("reessaie", "réessaie"),
    ("Numero de telephone guineen", "Numéro de téléphone guinéen"),
    ("Numero", "Numéro"),
    ("Email ou telephone requis", "Email ou téléphone requis"),
    ("L'universite est requise pour un etudiant", "L'université est requise pour un étudiant"),
    ("La filiere est requise pour un etudiant", "La filière est requise pour un étudiant"),
    ("2000 caracteres max", "2000 caractères max"),
    ("Cles push invalides", "Clés push invalides"),
    ("Acces admin requis", "Accès admin requis"),
    ("Acces refuse", "Accès refusé"),
    ("Seuls les etudiants peuvent devenir conseillers", "Seuls les étudiants peuvent devenir conseillers"),
    ("Identifiant etudiant requis pour repondre", "Identifiant étudiant requis pour répondre"),
    ("Aucune conversation avec cet etudiant", "Aucune conversation avec cet étudiant"),
    ("Identifiant etudiant requis", "Identifiant étudiant requis"),
    ("Le commentaire ne peut pas etre vide", "Le commentaire ne peut pas être vide"),
    ("Element introuvable", "Élément introuvable"),
    ("Role invalide", "Rôle invalide"),
    ("non autorise", "non autorisé"),
    ("acceptees", "acceptées"),
    ("Duree", "Durée"),
    ("Telephone", "Téléphone"),
    ("Prerequis", "Prérequis"),
    ("Cree ton compte", "Crée ton compte"),
    ("Cree", "Crée"),
    ("reunis au meme", "réunis au même"),
    ("meme endroit", "même endroit"),
    ("C'est ca", "C'est ça"),
    ("apres le bac", "après le bac"),
    ("opportunites en Guinee", "opportunités en Guinée"),
    ("filieres et universites", "filières et universités"),
    ("Trouve des etudiants deja en filiere", "Trouve des étudiants déjà en filière"),
    ("repondre a tes questions", "répondre à tes questions"),
    ("partager leur experience", "partager leur expérience"),
    ("temoignages d'etudiants", "témoignages d'étudiants"),
    ("generateur de CV", "générateur de CV"),
    ("Tu es pret", "Tu es prêt"),
    ("a ton rythme", "à ton rythme"),
    ("en haut a droite", "en haut à droite"),
    ("gerer ton compte", "gérer ton compte"),
    ("debouche local", "débouché local"),
    ("Scenario reel Guinee", "Scénario réel Guinée"),
    ("bacheliere en SM", "bachelière en SM"),
    ("mentorante", "mentorante"),  # might be intentional portmanteau
    ("echanges avec", "échanges avec"),
    ("Tu hesites entre", "Tu hésites entre"),
    ("demarrage", "démarrage"),
    ("demarrer une conversation", "démarrer une conversation"),
    ("Passionne par", "Passionné par"),
    ("Seuls les etudiants", "Seuls les étudiants"),
    ("Tu es maintenant conseiller", "Tu es maintenant conseiller"),
    ("En tant qu'etudiant", "En tant qu'étudiant"),
    ("Nouveau bachelier", "Nouveau bachelier"),
    ("Creation...", "Création..."),
    ("credits DeepSeek epuises", "crédits DeepSeek épuisés"),
    ("epuises", "épuisés"),
    ("Delai depasse", "Délai dépassé"),
    ("demarree", "démarrée"),
    ("recuperer le quota", "récupérer le quota"),
    ("Legal", "Légal"),
    ("Communaute", "Communauté"),
    ("communaute", "communauté"),
    ("experience", "expérience"),
    ("Categorie", "Catégorie"),
    ("categorie", "catégorie"),
    ("resultats", "résultats"),
    # Mots simples (après les expressions)
    ("Guinee", "Guinée"),
    ("Mathematiques", "Mathématiques"),
    ("Medecine", "Médecine"),
    ("medecine", "médecine"),
    ("Ingenierie", "Ingénierie"),
    ("Genie", "Génie"),
    ("electrique", "électrique"),
    ("mecanique", "mécanique"),
    ("Mecanique", "Mécanique"),
    ("Superieur", "Supérieur"),
    ("superieur", "supérieur"),
    ("Agronomique", "Agronomique"),
    ("Veterinaire", "Vétérinaire"),
    ("Geologie", "Géologie"),
    ("Securite", "Sécurité"),
    ("securite", "sécurité"),
    ("guineenne", "guinéenne"),
    ("guineen", "guinéen"),
    ("specialisee", "spécialisée"),
    ("specialise", "spécialisé"),
    ("creee", "créée"),
    ("etablissements", "établissements"),
    ("etablissement", "établissement"),
    ("Etablissements", "Établissements"),
    ("Etablissement", "Établissement"),
    ("economiques", "économiques"),
    ("Economiques", "Économiques"),
    ("Economie", "Économie"),
    ("deuxieme", "deuxième"),
    ("situee a", "située à"),
    ("situe a", "situé à"),
    ("forestiere", "forestière"),
    ("francais", "français"),
    ("Reseaux", "Réseaux"),
    ("reseau", "réseau"),
    ("deja", "déjà"),
    ("etudes", "études"),
    ("metier", "métier"),
    ("interet", "intérêt"),
    ("apres", "après"),
    ("tres", "très"),
    ("decourager", "décourager"),
    ("N'ecris", "N'écris"),
    ("inconvenients", "inconvénients"),
    ("Non precises", "Non précisés"),
    ("precisement", "précisément"),
    ("verifie", "vérifie"),
    ("infirmieres", "infirmières"),
    ("juridiques", "juridiques"),
    ("preparation", "préparation"),
    ("realistes", "réalistes"),
    ("realiste", "réaliste"),
    ("dediee", "dédiée"),
    ("guineens", "guinéens"),
    ("debouches", "débouchés"),
    ("filiere", "filière"),
    ("Filiere", "Filière"),
    ("filieres", "filières"),
    ("Filieres", "Filières"),
    ("universite", "université"),
    ("Universite", "Université"),
    ("universites", "universités"),
    ("etudiant", "étudiant"),
    ("Etudiant", "Étudiant"),
    ("etudiants", "étudiants"),
    ("Etudiants", "Étudiants"),
    ("etudiante", "étudiante"),
    ("Etudiante", "Étudiante"),
    ("Annee", "Année"),
    ("annee", "année"),
    ("telephone", "téléphone"),
    ("reponse", "réponse"),
    ("reponses", "réponses"),
    ("Reponses", "Réponses"),
    ("bientot", "bientôt"),
    ("academique", "académique"),
    ("acces", "accès"),
    ("Acces", "Accès"),
    ("donnees", "données"),
    ("Donnees", "Données"),
    ("donnee", "donnée"),
    ("numero", "numéro"),
    ("ecrit", "écrit"),
    ("Ecris", "Écris"),
    ("ecris", "écris"),
    ("repondre", "répondre"),
    ("repondent", "répondent"),
    ("reussite", "réussite"),
    ("reussie", "réussie"),
    ("reussi", "réussi"),
    ("echouee", "échouée"),
    ("expiree", "expirée"),
    ("refusee", "refusée"),
    ("refuse", "refusé"),
    ("caracteres", "caractères"),
    ("enregistree", "enregistrée"),
    ("personnalisee", "personnalisée"),
    ("personnalise", "personnalisé"),
    ("adaptees", "adaptées"),
    ("adaptee", "adaptée"),
    ("publiees", "publiées"),
    ("publiee", "publiée"),
    ("publies", "publiés"),
    ("publie", "publié"),
    ("notifie", "notifié"),
    ("envoye", "envoyé"),
    ("reserve", "réservé"),
    ("trouve", "trouvé"),
    ("trouvee", "trouvée"),
    ("etudier", "étudier"),
    ("prive", "privé"),
    ("privee", "privée"),
    ("privees", "privées"),
    ("prives", "privés"),
    ("integree", "intégrée"),
    ("legale", "légale"),
    ("legales", "légales"),
    ("amelioration", "amélioration"),
    ("ameliorer", "améliorer"),
    ("utilisees", "utilisées"),
    ("utilisee", "utilisée"),
    ("securiser", "sécuriser"),
    ("chiffree", "chiffrée"),
    ("conservees", "conservées"),
    ("effacons", "effaçons"),
    ("traitees", "traitées"),
    ("etre", "être"),
    ("mise a jour", "mise à jour"),
    ("protege", "protège"),
    ("bibliotheque", "bibliothèque"),
    ("Decouvre", "Découvre"),
    ("Decris", "Décris"),
    ("Complete", "Complète"),
    ("Developpe", "Développe"),
    ("Generateur", "Générateur"),
    ("generateur", "générateur"),
    ("Creer", "Créer"),
    ("creer", "créer"),
    ("Region", "Région"),
    ("region", "région"),
    ("Prefecture", "Préfecture"),
    ("prefecture", "préfecture"),
    ("Departement", "Département"),
    ("departement", "département"),
    ("Photovotaique", "Photovoltaïque"),
    ("Mettalurgie", "Métallurgie"),
    ("Energétique", "Énergétique"),
    ("Energetique", "Énergétique"),
    ("Connait", "Connaît"),
    ("connait", "connaît"),
    ("hesites", "hésites"),
    ("Hesites", "Hésites"),
    ("Gere", "Gère"),
    ("gere", "gère"),
    ("pret", "prêt"),
    ("ca ", "ça "),
    (" ca,", " ça,"),
    (" ca.", " ça."),
    (" ca?", " ça?"),
    ("meme ", "même "),
    ("tres ", "très "),
    ("tres.", "très."),
    ("tres,", "très,"),
]

EXTENSIONS = {".tsx", ".ts", ".py"}
SKIP_DIRS = {"node_modules", ".next", "__pycache__", ".git", "dist", "build"}


def protect(content: str) -> str:
    for original, placeholder in PROTECTED:
        content = content.replace(original, placeholder)
    return content


def unprotect(content: str) -> str:
    for original, placeholder in PROTECTED:
        content = content.replace(placeholder, original)
    return content


def fix_content(content: str) -> str:
    content = protect(content)
    for old, new in REPLACEMENTS:
        if old in content:
            content = content.replace(old, new)
    content = unprotect(content)
    return content


def main() -> None:
    changed_files: list[Path] = []
    for path in ROOT.rglob("*"):
        if path.suffix not in EXTENSIONS:
            continue
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        rel = path.relative_to(ROOT)
        if str(rel).startswith("scripts" + path.anchor) or "scripts" in path.parts and path.name != "fix_accents.py":
            if "scripts" in path.parts and path.parent.name == "scripts" and path.suffix == ".py" and path.name != "fix_accents.py":
                pass  # skip other scripts unless they're in app
        # Only process okampus-app/src and okampus-api/app
        parts = path.parts
        if "okampus-app" in parts and "src" in parts:
            pass
        elif "okampus-api" in parts and "app" in parts:
            pass
        else:
            continue

        original = path.read_text(encoding="utf-8")
        fixed = fix_content(original)
        if fixed != original:
            path.write_text(fixed, encoding="utf-8")
            changed_files.append(path)
            print(f"Fixed: {rel}")

    print(f"\nTotal: {len(changed_files)} files updated")


if __name__ == "__main__":
    main()
